/*
 * This source file was generated by the Gradle 'init' task
 */
package javaproject1;

import java.sql.Connection;

import javaproject1.DAL.DataBase.DBConnection;

public class Main {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
    Connection conn = DBConnection.getConnection();
    if (conn != null) {
        System.out.println("Connected successfully!");
    }
}
}
